//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaneBolum
    {
        public int hastaneBolumID { get; set; }
        public Nullable<int> bolumID { get; set; }
        public Nullable<int> hastaneID { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual Hastane Hastane { get; set; }
    }
}
