//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciBilgileri
    {
        public int kullaniID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public Nullable<int> ilID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public string acikAdres { get; set; }
    
        public virtual Il Il { get; set; }
        public virtual Ilce Ilce { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
